name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --name my-webapp-app \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label mywebappdemo123 \
            --ports 3001
